#pragma once

#include <optional>
#include "kivo/playback/control_plane/revision/revision_master_model.hpp"
#include "kivo/playback/control_plane/revision/cancellation.hpp"
#include "kivo/playback/control_plane/control/seek_target.hpp"
#include "kivo/playback/control_plane/primitives/time_types.hpp"
#include "kivo/playback/control_plane/primitives/value_types.hpp"

namespace kivo::playback::control_plane::command {

/// PlaybackCommandType enumerates external command types.
enum class PlaybackCommandType
{
    Play,
    Pause,
    Seek,
    Stop,
    Flush,
    SetPlaybackRate,
    RequestUserTrackSwitch,
    RequestShutdown
};

/// CommandPriority enumerates command priority levels.
enum class CommandPriority
{
    Normal,
    Critical,
    Emergency
};

/// FlushScope enumerates flush scope.
enum class FlushScope
{
    CurrentStream,
    AllStreams
};

/// UserTrackSwitchRequest is the only track-switch shape P8 may submit.
/// P8 must NOT directly submit a TrackSwitchPlan; authorization happens
/// through AuthorizedPlaybackControlPort (P4G-024).
struct UserTrackSwitchRequest
{
    primitives::U64 track_hint{0};
    bool relative{false};
};

/// PlaybackCommandRequest is the external command request shape.
/// CommandId / CommandSequence / submitted_at are NOT set here; only the
/// P4 submit path assigns them (see PlaybackCommand).
struct PlaybackCommandRequest
{
    PlaybackCommandType type{PlaybackCommandType::Play};
    CommandPriority priority{CommandPriority::Normal};
    std::optional<control::SeekTarget> seek_target{};
    std::optional<FlushScope> flush_scope{};
    std::optional<primitives::Milliseconds> playback_rate{};
    std::optional<UserTrackSwitchRequest> user_track_switch_request{};
    revision::CancellationToken cancellation_override{};
};

/// PlaybackCommand is the internal, fully-attributed command record.
/// id / sequence / generation / submitted_at are only generated by the P4
/// submit path. External code must NOT construct this directly.
struct PlaybackCommand
{
    revision::CommandId id{};
    revision::CommandSequence sequence{};
    revision::SessionGeneration generation{};
    primitives::MonotonicTimestamp submitted_at{};
    PlaybackCommandRequest request{};
};

} // namespace kivo::playback::control_plane::command
