#pragma once

#include "kivo/playback/control_plane/primitives/value_types.hpp"

namespace kivo::playback::control_plane::control {

/// EmergencyControlLane provides preemption without SeekEpoch.
/// SeekEpoch only generated by Control Thread when consuming SeekCommand.
/// Emergency Lane only does preemption, wake, atomic flag.
/// Must NOT allocate heap. Must NOT call user callback.
class EmergencyControlLane
{
public:
    void request_stop() noexcept { stop_requested_ = true; }
    void request_seek_fence() noexcept { seek_fence_requested_ = true; }
    void request_shutdown() noexcept { shutdown_requested_ = true; }

    bool stop_requested() const noexcept { return stop_requested_; }
    bool seek_fence_requested() const noexcept { return seek_fence_requested_; }
    bool shutdown_requested() const noexcept { return shutdown_requested_; }

    void wake_control_thread() noexcept { /* platform-specific wake */ }
    void wake_reader_waiters() noexcept { /* platform-specific wake */ }

private:
    bool stop_requested_{false};
    bool seek_fence_requested_{false};
    bool shutdown_requested_{false};
};

} // namespace kivo::playback::control_plane::control
